# Generated by Django 3.1.4 on 2021-12-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atcoder_contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestId', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('startTime', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
