# Generated by Django 3.1.4 on 2021-01-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20210106_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcoder_contest',
            name='contestId',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='prob_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
