# Generated by Django 3.1.4 on 2020-12-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contestId', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=50)),
                ('startTime', models.CharField(blank=True, max_length=50, null=True)),
                ('participants', models.CharField(blank=True, max_length=6, null=True)),
                ('Type', models.CharField(choices=[('R', 'Regular'), ('G', 'Gym')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('current', models.CharField(max_length=6)),
                ('total', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('current', models.CharField(max_length=6)),
                ('total', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('handle', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=4)),
                ('maxRating', models.CharField(max_length=4)),
                ('rank', models.CharField(max_length=50)),
                ('maxRank', models.CharField(max_length=50)),
                ('worldRank', models.CharField(blank=True, max_length=6, null=True)),
                ('countryRank', models.CharField(blank=True, max_length=6, null=True)),
                ('organizationRank', models.CharField(blank=True, max_length=6, null=True)),
                ('photoUrl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_contest_rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worldRank', models.CharField(max_length=6)),
                ('countryRank', models.CharField(blank=True, max_length=6, null=True)),
                ('organizationRank', models.CharField(blank=True, max_length=6, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='contestRank',
            field=models.ManyToManyField(through='codeforces.user_contest_rank', to='codeforces.contest'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeforces.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeforces.organization'),
        ),
        migrations.CreateModel(
            name='organization_contest_participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.CharField(max_length=6)),
                ('total', models.CharField(max_length=6)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.contest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.organization')),
            ],
        ),
        migrations.CreateModel(
            name='country_contest_participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.CharField(max_length=6)),
                ('total', models.CharField(max_length=6)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.contest')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.country')),
            ],
        ),
    ]
