# Generated by Django 3.1.4 on 2020-12-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization_contest_participation',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='organization_contest_participation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='country',
            name='current',
        ),
        migrations.RemoveField(
            model_name='country',
            name='total',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='current',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='total',
        ),
        migrations.RemoveField(
            model_name='user',
            name='countryRank',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organizationRank',
        ),
        migrations.RemoveField(
            model_name='user',
            name='worldRank',
        ),
        migrations.RemoveField(
            model_name='user_contest_rank',
            name='countryRank',
        ),
        migrations.RemoveField(
            model_name='user_contest_rank',
            name='organizationRank',
        ),
        migrations.DeleteModel(name='country_contest_participation', ),
        migrations.DeleteModel(name='organization_contest_participation', ),
    ]
