# Generated by Django 3.1.4 on 2020-12-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0002_auto_20201223_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_contest_rank',
            name='worldRank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
