# Generated by Django 3.1.4 on 2021-01-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0004_auto_20201224_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='isUpdated',
            field=models.BooleanField(default=False),
        ),
    ]
