# Generated by Django 3.1.4 on 2021-01-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0005_contest_isupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='maxRank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
