# Generated by Django 3.1.4 on 2021-01-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0006_auto_20210106_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
