# Generated by Django 3.1.4 on 2021-01-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0007_auto_20210106_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contestId',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True,
                                   db_index=True,
                                   max_length=50,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True,
                                   db_index=True,
                                   max_length=50,
                                   null=True),
        ),
    ]
