# Generated by Django 3.1.4 on 2021-09-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0008_auto_20210129_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='maxRank',
            field=models.CharField(blank=True,
                                   default='UnRated',
                                   max_length=50,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='maxRating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True,
                                   default='UnRated',
                                   max_length=50,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
