# Generated by Django 3.1.4 on 2021-11-16 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20210129_2145'),
        ('codeforces', '0009_auto_20210929_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeforcesProblemSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_problem', to='problem.problem')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_problem', to='problem.problem')),
            ],
        ),
    ]
