# Generated by Django 3.1.4 on 2021-10-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordwebhook',
            name='username',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='discordwebhook',
            name='webhook_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='discordwebhook',
            name='webhook_token',
            field=models.CharField(max_length=128),
        ),
    ]
