# Generated by Django 3.1.4 on 2021-01-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
