# Generated by Django 3.1.4 on 2021-01-02 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('description',
                 models.TextField(blank=True, max_length=400, null=True)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isTopicWise', models.BooleanField(default=True)),
                ('type_list',
                 models.CharField(choices=[('1', 'List'), ('2', 'Ladder'),
                                           ('3', 'Both')],
                                  default='1',
                                  max_length=1)),
                ('slug',
                 models.SlugField(blank=True, max_length=35, unique=True)),
                ('owner',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('problem',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='prob',
                                   to='problem.problem')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='user',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListInfo',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('description',
                 models.TextField(blank=True, max_length=400, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True,
                                                  null=True)),
                ('p_list',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='curr_list',
                                   to='lists.list')),
                ('problem',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='curr_prob',
                                   to='problem.problem')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.AddField(
            model_name='list',
            name='problem',
            field=models.ManyToManyField(related_name='problem',
                                         through='lists.ListInfo',
                                         to='problem.Problem'),
        ),
    ]
