# Generated by Django 3.1.4 on 2020-12-23 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=255)),
                ('description', models.TextField(default=' ', max_length=400)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isTopicWise', models.BooleanField(default=True)),
                ('type_list', models.CharField(choices=[('1', 'List'), ('2', 'Ladder'), ('3', 'Both')], default='1', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prob', to='problem.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default=' ', max_length=400)),
                ('p_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curr_list', to='lists.list')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curr_prob', to='problem.problem')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='problem',
            field=models.ManyToManyField(related_name='problem', through='lists.ListInfo', to='problem.Problem'),
        ),
    ]
