# Generated by Django 3.1.4 on 2021-01-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='listinfo',
            name='added_at',
        ),
    ]
