# Generated by Django 3.1.4 on 2020-12-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20201224_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='list',
            name='type_list',
            field=models.CharField(choices=[('1', 'List'), ('2', 'Ladder'), ('3', 'Both')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='listinfo',
            name='description',
            field=models.TextField(blank=True, default=' ', max_length=400, null=True),
        ),
    ]
