# Generated by Django 3.1.4 on 2020-12-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20201221_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='isList',
        ),
        migrations.AddField(
            model_name='list',
            name='type_list',
            field=models.CharField(choices=[('1', 'List'), ('2', 'Ladder'), ('3', 'Both')], default='1', max_length=10),
        ),
    ]
