# Generated by Django 3.1.4 on 2020-12-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20201224_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
