# Generated by Django 3.1.4 on 2020-12-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20201222_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listinfo',
            old_name='curr_list',
            new_name='l',
        ),
    ]
