# Generated by Django 3.1.4 on 2021-02-01 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0004_listextrainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadderStarted',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('ladder',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='ladder',
                                   to='lists.list')),
                ('ladder_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='ladder_user',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
