# Generated by Django 3.1.4 on 2020-12-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20201223_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinfo',
            name='description',
            field=models.TextField(blank=True, default=' ', max_length=400),
        ),
    ]
