# Generated by Django 3.1.4 on 2020-12-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20201224_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, default=' ', max_length=400, null=True),
        ),
    ]
