# Generated by Django 3.1.4 on 2022-01-01 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0006_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='enroll_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enroll_list', to='lists.list'),
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_user', to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='lists.list')),
            ],
        ),
    ]
