# Generated by Django 3.1.4 on 2020-12-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20201224_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(blank=True, max_length=35, unique=True),
        ),
    ]
