# Generated by Django 3.2.8 on 2022-01-14 12:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0008_editormodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditorModel',
            new_name='Editor',
        ),
    ]
