# Generated by Django 3.1.4 on 2020-12-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gurus',
            field=models.CharField(default='', max_length=300),
        ),
    ]
