# Generated by Django 3.1.4 on 2021-01-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201228_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gurus',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
