# Generated by Django 3.1.4 on 2020-12-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_gurus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gurus',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
