# Generated by Django 3.1.4 on 2021-01-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201229_2120'),
        ('user', '0003_profile_gurus'),
    ]

    operations = []
