# Generated by Django 3.1.4 on 2021-10-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord_tag',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_discord_verified',
            field=models.BooleanField(default=False),
        ),
    ]
