# Generated by Django 3.1.4 on 2021-10-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211011_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discord_tag',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
