# Generated by Django 3.1.4 on 2021-10-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codechefcontestproblems',
            name='problemid',
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
