# Generated by Django 3.1.4 on 2021-12-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('handle', models.CharField(db_index=True, max_length=50, unique=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('maxRating', models.IntegerField(blank=True, default=0, null=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('country_rank', models.IntegerField(blank=True, default=0, null=True)),
                ('global_rank', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
