# Generated by Django 3.1.4 on 2021-12-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechef', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
