# Generated by Django 3.1.4 on 2021-12-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechef', '0003_user_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechefcontest',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
