# Generated by Django 3.1.4 on 2021-12-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechef', '0004_auto_20211213_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contests_given',
            field=models.ManyToManyField(to='codechef.CodechefContest'),
        ),
    ]
