# Generated by Django 3.1.4 on 2021-01-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20210121_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='duration',
            field=models.DurationField(default=7200000000),
        ),
    ]
