# Generated by Django 3.1.4 on 2021-01-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20210121_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestresult',
            name='verdict',
        ),
        migrations.AddField(
            model_name='contestresult',
            name='penalty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestresult',
            name='submissionTime',
            field=models.DurationField(),
        ),
    ]
