# Generated by Django 3.1.4 on 2021-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20210121_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='isGym',
            field=models.BooleanField(default=False),
        ),
    ]
