# Generated by Django 3.1.4 on 2021-02-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_contest_isgym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='isGym',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='isMentorOn',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='isProblem',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='numberOfProblem',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='tag',
        ),
    ]
