# Generated by Django 3.1.4 on 2021-02-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20210203_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='numberOfProblem',
            field=models.IntegerField(default=5),
        ),
    ]
