# Generated by Django 3.1.4 on 2021-02-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_contest_numberofproblem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='numberOfProblem',
        ),
    ]
