# Generated by Django 3.1.4 on 2021-03-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0008_auto_20210129_2145'),
        ('contest', '0009_remove_contest_numberofproblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeforcesContest',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('contestId', models.IntegerField()),
                ('groupId',
                 models.CharField(blank=True, default=' ', max_length=20)),
                ('name',
                 models.CharField(blank=True, default=' ', max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('nproblems', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CodeforcesContestParticipation',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('participantId', models.IntegerField()),
                ('isOfficial', models.BooleanField()),
                ('isVirtual', models.BooleanField()),
                ('contest',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='contest.codeforcescontest')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='codeforces.user')),
            ],
        ),
        migrations.CreateModel(
            name='CodeforcesContestSubmission',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('isSolved', models.BooleanField()),
                ('submissionId', models.IntegerField()),
                ('problemIndex', models.IntegerField()),
                ('penalty', models.IntegerField()),
                ('lang', models.CharField(max_length=50)),
                ('participant',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='contest.codeforcescontestparticipation')),
            ],
        ),
    ]
