# Generated by Django 3.1.4 on 2021-03-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest',
         '0010_codeforcescontest_codeforcescontestparticipation_codeforcescontestsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeforcescontestsubmission',
            name='isSolved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='codeforcescontestsubmission',
            name='lang',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='codeforcescontestsubmission',
            name='penalty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='codeforcescontestsubmission',
            name='problemIndex',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='codeforcescontestsubmission',
            name='submissionId',
            field=models.IntegerField(null=True),
        ),
    ]
