# Generated by Django 3.1.4 on 2021-03-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20210312_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeforcescontest',
            name='showOnlyOfficial',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
